// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYoGJZEtfCck9oC_kkG5Bp-NK4yuiz1QM',
    appId: '1:949084502977:web:32ad761d85a3175f488d40',
    messagingSenderId: '949084502977',
    projectId: 'flit-crud-cf324',
    authDomain: 'flit-crud-cf324.firebaseapp.com',
    storageBucket: 'flit-crud-cf324.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqMTaRsWZa2M7D7QcHhf3q9Jqc7JifXrU',
    appId: '1:949084502977:android:ff0e5bbb8d86443a488d40',
    messagingSenderId: '949084502977',
    projectId: 'flit-crud-cf324',
    storageBucket: 'flit-crud-cf324.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3MsFwqS2NY2dQQNgoZ7pp-cqDN6xwBUo',
    appId: '1:949084502977:ios:b74b2e7ca710a001488d40',
    messagingSenderId: '949084502977',
    projectId: 'flit-crud-cf324',
    storageBucket: 'flit-crud-cf324.appspot.com',
    androidClientId: '949084502977-blvpnegt92icui89jdh475mint3me32m.apps.googleusercontent.com',
    iosClientId: '949084502977-r3rqjduspob29ad44jiumdb1pljn3lit.apps.googleusercontent.com',
    iosBundleId: 'com.example.burgershort',
  );
}
